name: example-environment

dependencies:
  - bokeh=0.12.4
  - scipy=0.19.0
  - matplotlib=2.0.1
  - datashader=0.4.0
  - param=1.5.1
  - scikit-learn=0.18.1
  - notebook=4
  - pip:
    - git+https://github.com/ioam/paramnb.git#egg=paramnb

